from PointSystem import *

set = points(0, classifier="Points", front=True)
print(set.points)
set.set(32)
print(set.points)
set.div(2)
print(set.points)
set.set(56)
print(set.points)
set.div(3)
print(set.points)
set.round()
print(set.points)
set.float()
print(set.points)
set.reset()
print(set.points)
set.add(32)
print(set.points)
set.show()
print(set.points)